[tox]
envlist =
    py314
    py313
    py312
    py311
    py310
    ruff
    mypy
isolated_build = True

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    pytest
    pytest-cov
commands =
    pytest --cov=hdl_encrypt --cov-report=term-missing tests/

[testenv:ruff]
deps =
    ruff
commands =
    ruff check src/ tests/
    ruff format --check src/ tests/

[testenv:mypy]
deps =
    mypy
    cryptography
    pytest
commands =
    mypy src/ tests/
